config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'albums#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :albums
end

app/models/album.rb
class Album < ApplicationRecord
  # has_attached_file :images, styles: { medium: "300x300>", thumb: "100x100>" }
  # validates_attachment_content_type :images, content_type: /\Aimage\/.*\z/
  has_many :attachments
  validates :title, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :album

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: %r/\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_user!

  def index
    @albums = Album.all
  end

  def show
    @album = Album.find(params[:id])
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to @album
    else
      redirect_to :new, status: :see_other
    end
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])

    if @album.update(album_params)
      redirect_to @album
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    def album_params
      params.require(:album).permit(:title,:images)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_form.html.erb
<%= form_for @album, url: album_path, html: { multipart: true } do |form| %>
<div>
    <%= form.label :title %>
    <%= form.text_field :title %>
</div>
<div>
    <%= form.label :images %>
    <%= form.file_field :images %>
</div>
<div>
    <%= form.submit %>
</div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editar album</h1>
<hr>
<%= render "albums/form" %>

app/views/albums/index.html.erb
<h1>Albums</h1>
<hr>
<%= link_to "Nuevo",new_album_path %>
<hr>
<ul>
    <% @albums.each do |album| %>
        <li><%= link_to image_tag(album.images.url(:thumb)), album_path(album) %></li>
    <% end %>
</ul>

app/views/albums/new.html.erb
<h1>Nuevo album</h1>
<hr>
<%= form_for @album, url: albums_path, html: { multipart: true } do |form| %>
<div>
    <%= form.label :title %>
    <%= form.text_field :title %>
</div>
<div>
    <%= form.label :images %>
    <%= form.file_field :images %>
</div>
<div>
    <%= form.submit %>
</div>
<% end %>

app/views/albums/show.html.erb
<h1><%= @album.title %></h1>
<hr>
<%= link_to "Volver", albums_path %> |
<%= link_to "Editar", edit_album_path(@album) %>
<hr>
<%= image_tag @album.images.url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RrGallery</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>